export function createSeedState() {
  const now = new Date().toISOString();
  return {
    session: null,
    receipts: [
      {
        id: "recv-1001",
        batch_id: "FR-2026-0415-01",
        status: "approved",
        delivery_allowed: true,
        supplier: { id: "sup-001", name: "Farmlane" },
        supplier_name: "Farmlane",
        strain_name: "Blue Dream",
        expected_weight_lbs: 350,
        expected_potency_pct: 23.5,
        offered_price_per_lb: 285,
        purchase_date: "2026-04-15",
        availability_date: "2026-04-15",
        submitted_at: now,
        delivery_needed: true,
        clean_or_dirty: "clean",
        receiving: {
          queue_state: "ready",
          location: "",
          floor_state: "receiving",
          lot_count: 1,
          photo_count: 0,
        },
        lots: [
          {
            id: "lot-1001",
            tracking_id: "LOT-1001ABCD",
            strain_name: "Blue Dream",
            weight_lbs: 350,
            remaining_weight_lbs: 350,
            potency_pct: 23.5,
            floor_state: "receiving",
            location: "",
          },
        ],
        photos: [],
        approval: {
          approved_at: "2026-04-15T12:00:00.000Z",
          approved_by_name: "Admin User",
        },
        delivery: null,
      },
      {
        id: "recv-1002",
        batch_id: "CR-2026-0414-02",
        status: "committed",
        delivery_allowed: true,
        supplier: { id: "sup-002", name: "Cedar Ridge Cultivation" },
        supplier_name: "Cedar Ridge Cultivation",
        strain_name: "Sour Diesel",
        expected_weight_lbs: 210,
        expected_potency_pct: 21.2,
        offered_price_per_lb: 270,
        purchase_date: "2026-04-14",
        availability_date: "2026-04-14",
        submitted_at: now,
        delivery_needed: true,
        clean_or_dirty: "clean",
        receiving: {
          queue_state: "ready",
          location: "Dock A",
          floor_state: "receiving",
          lot_count: 1,
          photo_count: 1,
        },
        lots: [
          {
            id: "lot-1002",
            tracking_id: "LOT-1002BCDE",
            strain_name: "Sour Diesel",
            weight_lbs: 210,
            remaining_weight_lbs: 210,
            potency_pct: 21.2,
            floor_state: "receiving",
            location: "Dock A",
          },
        ],
        photos: [
          {
            id: "ph-1002",
            url: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSczMjAnIGhlaWdodD0nMzIwJz48cmVjdCB3aWR0aD0nMzIwJyBoZWlnaHQ9JzMyMCcgZmlsbD0nI2YwZTdkNScvPjx0ZXh0IHg9JzUwJScgeT0nNDglJyBmb250LXNpemU9JzI0JyBmaWxsPScjMWMxYzEnIHRleHQtYW5jaG9yPSdtaWRkbGUnPkRvY2sgQSBwYWxsZXQ8L3RleHQ+PHRleHQgeD0nNTAlJyB5PSc1OCUnIGZvbnQtc2l6ZT0nMTgnIGZpbGw9JyMxYzFjMScgdGV4dC1hbmNob3I9J21pZGRsZSc+UmVjZWl2aW5nIHByZXZpZXc8L3RleHQ+PC9zdmc+",
            photo_context: "delivery",
            name: "dock-preview.svg",
          },
        ],
        approval: {
          approved_at: "2026-04-14T15:00:00.000Z",
          approved_by_name: "Buyer Lead",
        },
        delivery: null,
      },
      {
        id: "recv-1003",
        batch_id: "BC-2026-0409-03",
        status: "delivered",
        delivery_allowed: false,
        supplier: { id: "sup-003", name: "Blue Coast Farms" },
        supplier_name: "Blue Coast Farms",
        strain_name: "GMO",
        expected_weight_lbs: 180,
        expected_potency_pct: 25.1,
        offered_price_per_lb: 315,
        purchase_date: "2026-04-09",
        availability_date: "2026-04-09",
        submitted_at: now,
        delivery_needed: false,
        clean_or_dirty: "clean",
        receiving: {
          queue_state: "closed",
          location: "Receiving Vault",
          floor_state: "receiving",
          lot_count: 1,
          photo_count: 1,
        },
        lots: [
          {
            id: "lot-1003",
            tracking_id: "LOT-1003CDEF",
            strain_name: "GMO",
            weight_lbs: 178.4,
            remaining_weight_lbs: 178.4,
            potency_pct: 25.0,
            floor_state: "receiving",
            location: "Receiving Vault",
          },
        ],
        photos: [
          {
            id: "ph-1003",
            url: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSczMjAnIGhlaWdodD0nMzIwJz48cmVjdCB3aWR0aD0nMzIwJyBoZWlnaHQ9JzMyMCcgZmlsbD0nI2RlZmFnZScvPjx0ZXh0IHg9JzUwJScgeT0nNDglJyBmb250LXNpemU9JzI0JyBmaWxsPScjMWMxYzEnIHRleHQtYW5jaG9yPSdtaWRkbGUnPlJlY2VpcHQgY29uZmlybWVkPC90ZXh0Pjx0ZXh0IHg9JzUwJScgeT0nNTglJyBmb250LXNpemU9JzE4JyBmaWxsPScjMWMxYzEnIHRleHQtYW5jaG9yPSdtaWRkbGUnPlZhdWx0IHN0YWdlZCBsb3Q8L3RleHQ+PC9zdmc+",
            photo_context: "delivery",
            name: "received-vault.svg",
          },
        ],
        approval: {
          approved_at: "2026-04-08T14:00:00.000Z",
          approved_by_name: "Buyer Lead",
        },
        delivery: {
          delivered_weight_lbs: 178.4,
          delivery_date: "2026-04-09",
          testing_status: "completed",
          actual_potency_pct: 25.0,
          clean_or_dirty: "clean",
          delivery_notes: "Received with no issues",
          delivered_by_name: "Receiving Lead",
        },
      },
    ],
  };
}

export function cloneSeedState() {
  return JSON.parse(JSON.stringify(createSeedState()));
}
